# Apparently you can't access values that have a '-' in the name so
# you have to use index instead
{{ $include_cert_manager := index .Values.tags "tls-provisioning" }}
{{ if $include_cert_manager }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-key-pair
{{ end }}
